### ISSUE TITLE
Consider adding a sample_limit to scrape jobs

### ISSUE THREAD

**Issue by tomwilkie** [grafana/jsonnet-libs#145]
Consider adding a (configurable) sample_limit to scrape jobs as a way of protecting the Prometheus, and and any upstream remote_write endpoints, from abusive jobs.

**Comment by beorn7** [comment]
The sample limit is per target. It protects against metric explosions on a single target. It does not protect against an explosion in the number of targets (e.g. accidental deploy of many tiny pods exposing metrics). The latter is probably also less likely.

I think we should probably have some fairly high limit in general for sanity checks (can still be de-activated for specific cases, e.g. kube-state-metrics is a single target with an awful lot of metrics by design). I would then only go through the effort of a custom limit for "usual suspects" targets. (Currently, that would be notoriously buggy targets like the nginx-ingress or promtail.)

In any case, we should have warning alerts that warn before hitting any limit, and also look at the total load of a Prometheus server so that we know when we run out of capacity. (Mostly a problem of the one-Prometheus-per-cluster setup, as the one server has to swallow all the load. With a vertical sharding (one Prometheus per "service"), more services implicitly mean more servers so that only organic traffic growth plays a role.)

**Comment by tomwilkie** [comment]
> I think we should probably have some fairly high limit in general for sanity check

+1

>  would then only go through the effort of a custom limit for "usual suspects" targets. 

We have a specific scrape target for KSM, so we can special case this.

> In any case, we should have warning alerts that warn before hitting any limit, and also look at the total load of a Prometheus server so that we know when we run out of capacity.

+1

**Comment by beorn7** [comment]
**sigh** The time I need to fix this is now further reduced by the time I need to remove stale labels.
