### ISSUE TITLE
ksonnet-util refactoring for clarity

### ISSUE THREAD

**Issue by malcolmholmes** [grafana/jsonnet-libs#215]
Having given some talks recently demonstrating Tanka, at the start, I needed to add: `(import 'ksonnet-util/kausal.libsonnet')`. This makes no sense - what is "ksonnet" and what is "kausal"? (Other than a cool company that has now merged with Grafana Labs!!).

I suggest we make some adjustments to `ksonnet-util` to make it cleaner for newcomers. These suggestions currently include:
- [x] move `jaeger.libsonnet` somewhere more sensible - it is not relevant where it is #291 
- [ ] rename `ksonnet-util/kausal.libsonnet` to ~`tanka-util/util.libsonnet`~ `k8s-mixin/defaults.libsonnet` #293 
- [ ] make the addition of labels (a) optional (b) configurable
- [ ] make `prometheus-ksonnet` use the defaulted config value for label name

**Comment by sh0rez** [comment]
Counterproposal!

* ~~rename ksonnet-util/kausal.libsonnet to tanka-util/util.libsonnet~~
* integrate most of kausal.libsonnet into `kube-jsonnet/k`

**Comment by malcolmholmes** [comment]
> Counterproposal!
> 
> * ~rename ksonnet-util/kausal.libsonnet to tanka-util/util.libsonnet~
> * integrate most of kausal.libsonnet into `kube-jsonnet/k`

Valid proposal. What would happen to the bits that aren't part of 'most'?

And how soon can this merge in be done?

**Comment by ilpianista** [comment]
@sh0rez may you please clarify how this should work? Should the generator generate a kausal file for each version? Is there already something like that? If not, can you please provide the steps needed?

**Comment by sh0rez** [comment]
Hi, generation of kausal.libsonnet is most probably not needed, as the file is only a patch.

Currently, there are three code generators around:
* `ksonnet/ksonnet-gen`, old and deprecated but still in use, up to k8s 1.14
* `kube-jsonnet/k`, fork of `ksonnet-gen`
  * maintained by us and some folks at RedHat
  * up to k8s 1.18
  * unhealthy codebase, hard to maintain
* `jsonnet-libs/k8s`: my very alpha, experimental generator, hopefully the future

All of these have in common, that they _generate_ the overall library, but rely on _hand-written_ patches to provide extra features, such as constructors.

`k.libsonnet` is such a hand written file, wrapping around `k8s.libsonnet`, the generated one.

Because back then we didn't control `k.libsonnet`, `kausal.libsonnet` was created as another wrapper, adding what we needed.

To somehow break this mess, I currently focus on the newer generator `jsonnet-libs/k8s`, which will provide a framework for creating a much more flexible and clean library, once finished.  
Especially it will allow to add as many hand written patches as we need, effectively breaking kausal.libsonnet up into pieces, putting them where they belong and having a single library in the end, which base can be regenerated for each Kubernetes version.

Expect to see some progress there in the next three months.

**Comment by Duologic** [comment]
The ksonnet-util library has been refactored. Other issues and ideas should be expanded in new issues.
