### ISSUE TITLE
Traefik dashboards use $__interval and don't show anything by default in Grafana Cloud

### ISSUE THREAD

**Issue by regner** [grafana/jsonnet-libs#916]
When installing the Traefik dashboards they default to "Last 1 hour" for the time. This combined with the integration defaults having a 60 second scrape default means nothing actually gets displayed. The dashboards look empty. If you expand the time to "Last 3 hours" most of the panels suddenly get data.

I believe the problem is down to the usage of `$__interval` instead of `$__rate_interval` combined with the scape time being 60 seconds.

It probably makes sense to switch all of the `$__interval` values to `$__rate_interval` if I understand things. Which I might now.

**Comment by v-zhuravlev** [comment]
Using $__inteval is done on purpose to make sure that  increase() increments don't **overlap** and Totals calculation is correct. If we change it to $__rate_interval than totals calculation can be too high due to dynamic nature of $__rate_interval and overlapping of increase() increments.

![image](https://user-images.githubusercontent.com/14870891/216453322-756ef0a2-a208-4320-bdc0-10fca19af3eb.png)

Let me see if this can be fixed some other way.

**Comment by regner** [comment]
OK, I definetly did not/still do not understand that. I will be very interested in how to properly solve it.
